apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb
  # Tu peux ajouter d’autres propriétés Spring ici si besoin
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL-AUTO: update
  SPRING_JPA_SHOW-SQL: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n          # = "spring"  en base64
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz      # = "spring123" en base64

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: mahdimasmoudi/student-management   # remplace par ton vrai username/image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080          # port exposé dans le cluster
      targetPort: 8080    # port du container
      nodePort: 30080     # port accessible depuis l'extérieur (30000-32767)
